import './globals.css'
import type { Metadata } from 'next'
import { Outfit } from 'next/font/google'
import CustomProvider from './providers'

const font = Outfit({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly< {
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <CustomProvider>{children}</CustomProvider>
      </body>
    </html>
  )
}
