/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Ra0rm2akWda
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Gabarito } from 'next/font/google'

gabarito({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"

export function Component() {
  return (
    <div className="flex flex-col min-h-dvh">
      <header className="bg-background border-b px-4 md:px-6 h-14 flex items-center justify-between">
        <Link href="#" className="flex items-center gap-2" prefetch={false}>
          <SailboatIcon className="h-6 w-6" />
          <span className="font-bold text-lg">OpenSea</span>
        </Link>
        <nav className="flex items-center gap-4">
          <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
            Explore
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
            Create
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
            Profile
          </Link>
          <Button variant="outline" size="sm">
            Connect Wallet
          </Button>
        </nav>
      </header>
      <main className="flex-1 py-12 md:py-16 lg:py-20">
        <div className="container max-w-4xl px-4 md:px-6">
          <Card>
            <CardHeader>
              <CardTitle className="text-2xl font-bold">Create New Item</CardTitle>
              <CardDescription>Upload your image, add a title and description, and customize your NFT.</CardDescription>
            </CardHeader>
            <CardContent>
              <form className="grid gap-6">
                <div className="grid gap-2">
                  <Label htmlFor="image">Image, Video, Audio, or 3D Model</Label>
                  <div className="flex items-center justify-center rounded-lg border-2 border-dashed border-muted p-8">
                    <div className="text-center">
                      <div className="mx-auto h-8 w-8 text-muted-foreground" />
                      <p className="mt-4 text-sm text-muted-foreground">
                        JPG, PNG, GIF, SVG, MP4, WEBM, MP3, WAV, OGG, GLB, GLTF. Max 100MB.
                      </p>
                      <Button variant="outline" size="sm" className="mt-4">
                        Choose File
                      </Button>
                    </div>
                  </div>
                </div>
                <div className="grid gap-2">
                  <Label htmlFor="name">Name</Label>
                  <Input id="name" placeholder="Item name" />
                </div>
                <div className="grid gap-2">
                  <Label htmlFor="description">Description</Label>
                  <Textarea id="description" rows={3} placeholder="Provide a detailed description of your item" />
                </div>
                <div className="grid gap-2">
                  <Label htmlFor="properties">Properties</Label>
                  <div className="grid grid-cols-2 gap-4">
                    <div className="grid gap-2">
                      <Input id="property-1-key" placeholder="Property 1 Key" />
                      <Input id="property-1-value" placeholder="Property 1 Value" />
                    </div>
                    <div className="grid gap-2">
                      <Input id="property-2-key" placeholder="Property 2 Key" />
                      <Input id="property-2-value" placeholder="Property 2 Value" />
                    </div>
                    <div className="grid gap-2">
                      <Input id="property-3-key" placeholder="Property 3 Key" />
                      <Input id="property-3-value" placeholder="Property 3 Value" />
                    </div>
                    <div className="grid gap-2">
                      <Input id="property-4-key" placeholder="Property 4 Key" />
                      <Input id="property-4-value" placeholder="Property 4 Value" />
                    </div>
                  </div>
                </div>
                <div className="grid gap-2">
                  <Label htmlFor="levels">Levels</Label>
                  <div className="grid grid-cols-2 gap-4">
                    <div className="grid gap-2">
                      <Input id="level-1-key" placeholder="Level 1 Key" />
                      <Input id="level-1-value" placeholder="Level 1 Value" />
                    </div>
                    <div className="grid gap-2">
                      <Input id="level-2-key" placeholder="Level 2 Key" />
                      <Input id="level-2-value" placeholder="Level 2 Value" />
                    </div>
                    <div className="grid gap-2">
                      <Input id="level-3-key" placeholder="Level 3 Key" />
                      <Input id="level-3-value" placeholder="Level 3 Value" />
                    </div>
                    <div className="grid gap-2">
                      <Input id="level-4-key" placeholder="Level 4 Key" />
                      <Input id="level-4-value" placeholder="Level 4 Value" />
                    </div>
                  </div>
                </div>
                <div className="grid gap-2">
                  <Label htmlFor="songs">Songs</Label>
                  <div className="grid grid-cols-2 gap-4">
                    <div className="grid gap-2">
                      <Input id="song-1-key" placeholder="Song 1 Key" />
                      <Input id="song-1-value" placeholder="Song 1 Value" />
                    </div>
                    <div className="grid gap-2">
                      <Input id="song-2-key" placeholder="Song 2 Key" />
                      <Input id="song-2-value" placeholder="Song 2 Value" />
                    </div>
                    <div className="grid gap-2">
                      <Input id="song-3-key" placeholder="Song 3 Key" />
                      <Input id="song-3-value" placeholder="Song 3 Value" />
                    </div>
                    <div className="grid gap-2">
                      <Input id="song-4-key" placeholder="Song 4 Key" />
                      <Input id="song-4-value" placeholder="Song 4 Value" />
                    </div>
                  </div>
                  <Button variant="outline" size="sm" className="mt-4">
                    Add Song
                  </Button>
                </div>
                <div className="grid gap-2">
                  <Label htmlFor="royalty">Royalty</Label>
                  <div className="flex items-center gap-2">
                    <Input id="royalty" type="number" min="0" max="100" placeholder="10" />
                    <span>%</span>
                  </div>
                </div>
              </form>
            </CardContent>
            <CardFooter className="flex justify-end gap-2">
              <Button variant="outline">Cancel</Button>
              <Button>Create</Button>
            </CardFooter>
          </Card>
        </div>
      </main>
      <footer className="bg-muted-foreground text-background px-4 md:px-6 py-8 flex flex-col md:flex-row items-center justify-between gap-4">
        <div className="flex items-center gap-4">
          <Link href="#" prefetch={false}>
            <SailboatIcon className="h-6 w-6" />
          </Link>
          <p className="text-sm">© 2023 OpenSea. All rights reserved.</p>
        </div>
        <div className="flex items-center gap-4">
          <Link href="#" className="text-sm hover:underline" prefetch={false}>
            Twitter
          </Link>
          <Link href="#" className="text-sm hover:underline" prefetch={false}>
            Discord
          </Link>
          <Link href="#" className="text-sm hover:underline" prefetch={false}>
            Instagram
          </Link>
          <Link href="#" className="text-sm hover:underline" prefetch={false}>
            Blog
          </Link>
        </div>
      </footer>
    </div>
  )
}

function SailboatIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 18H2a4 4 0 0 0 4 4h12a4 4 0 0 0 4-4Z" />
      <path d="M21 14 10 2 3 14h18Z" />
      <path d="M10 2v16" />
    </svg>
  )
}


function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
